name: frontendgabarito
description: "Aplicativo de leitor de gabaritos via OCR e Câmera."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  google_mlkit_text_recognition: ^0.15.0
  shared_preferences: ^2.2.2
  camera: ^0.10.5+5
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

