name: gabarito_app
description: Aplicativo para correção de gabarito - UniALFA

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2

  # HTTP
  http: ^1.1.0

  # Storage
  shared_preferences: ^2.2.2

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # Camera
  camera: ^0.10.5+5
  image_picker: ^1.0.4

  # Utils
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
