name: frontendgabarito
description: "Aplicativo de leitor de gabaritos via OCR e Câmera."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

